### ISSUE TITLE
linux LTP so linkerror  无法打开共享对象文件

### ISSUE THREAD

**Issue by xinke0802** [HIT-SCIR/ltp#170]
jdk1.7的环境下编译了LTP，成功运行。但是其他机器使用编译生成的so文件的时候，出现下面的问题：
（jdk环境里已经拷贝了所有的so文件）

Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/xiaohuqi/work/ztb/libsegmentor_jni.so: libsegmentor.so.0.2.0: 无法打开共享对象文件: 没有那个文件或目录
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1957)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1882)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1843)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1061)
	at edu.hit.ir.ltp4j.Segmentor.<clinit>(Segmentor.java:11)
	at com.hiekn.wzh.ltp.util.LTPUtil.init(LTPUtil.java:81)
	at com.hiekn.wzh.Demo.main(Demo.java:31)

**Comment by carfly** [comment]
其它机器的.so是放到  /home/xiaohuqi/work/ztb/libsegmentor_jni.so 么？

**Comment by endyul** [comment]
是否配置了`java.library.path`
