### ISSUE TITLE
分词结果比较慢？

### ISSUE THREAD

**Issue by MrRace** [HIT-SCIR/ltp#375]
(1)分词似乎比较慢。试用了下，发现运行：
```
segment, hidden = ltp.seg(["我的句子"])
```
不管是small版还是tiny版，执行需要0.2s左右。这比pyltp慢了许多，请问有什么提速方案吗？谢谢！

(2)另外，目前不支持一次处理多个句子吗？比如：
```
segment, hidden = ltp.seg(["我的句子", "今天天气很的很不错,带你去爬山"])
```
报错如下：
```
File "/opt/conda/lib/python3.7/site-packages/ltp/ltp.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ltp/ltp.py", line 138, in seg
    tokenizerd = self.tokenizer.batch_encode_plus(inputs, return_tensors='pt')
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1831, in batch_encode_plus
    **kwargs,
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_fast.py", line 378, in _batch_encode_plus
    return BatchEncoding(sanitized, encodings, tensor_type=return_tensors)
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 159, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 515, in convert_to_tensors
    "Unable to create tensor, you should probably activate truncation and/or padding "
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.

```

**Comment by AlongWY** [comment]
1. 我们有一个onnx的加速方案，稍后会放出

**Comment by MrRace** [comment]
@AlongWY 模型加载时间没有统计在内。我统计的时候仅仅是`ltp.seg`这个语句的执行。

**Comment by carfly** [comment]
使用GPU，批量处理大规模的数据会好一些。

-Wanxiang (http://ir.hit.edu.cn/~car/)

**Comment by MrRace** [comment]
@carfly  我使用的是GPU，我还特地试了下传递参数`device='cuda'`，结果是一样的。你们那边测试的速度是多少？

**Comment by carfly** [comment]
就一个句子体现不出来GPU的优势……

-Wanxiang (http://ir.hit.edu.cn/~car/)

**Comment by AlongWY** [comment]
如果是单独一个句子，使用GPU甚至可能更慢，还要考虑内存到GPU的IO时间

**Comment by MrRace** [comment]
@AlongWY  使用 fastLTP 时候，分别试用了 `onnxruntime` 和`onnxruntime-gpu` 发现分别报错如下：
onnxruntime：
```
    ltp = FastLTP(path = LTP_MODEL_PATH)
  File "/opt/conda/lib/python3.7/site-packages/ltp/fastltp.py", line 37, in __init__
    self.onnx = rt.InferenceSession(onnx_path, so, providers=providers)
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers)
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
RuntimeError: Unknown Provider Type: GPUExecutionProvider

```
onnxruntime-gpu：
```
  ltp = FastLTP(path = LTP_MODEL_PATH, device='cuda')
  File "/opt/conda/lib/python3.7/site-packages/ltp/fastltp.py", line 37, in __init__
    self.onnx = rt.InferenceSession(onnx_path, so, providers=providers)
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers)
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
RuntimeError: Unknown Provider Type: GPUExecutionProvider
```
何解？

**Comment by AlongWY** [comment]
会自动导出ltp.onnx文件，你需要 CUDA_VISIBLE_DEVICES=-1 把 GPU ban 掉，onnx 在 windows 上会有问题

**Comment by MrRace** [comment]
@AlongWY 测试可以了。你们那边测试onnxruntime 和onnxruntime-gpu单条的测试速度分别是多少？

**Comment by AlongWY** [comment]
5000 句快 10s 左右

**Comment by HeroadZ** [comment]
今天发现了一个奇怪的错误，当list长度大于某个长度就会出错，具体是什么原因呢？
```
Traceback (most recent call last):
  File "src/preprocessing.py", line 79, in <module>
    Dataset().get_keywords()
  File "src/preprocessing.py", line 44, in get_keywords
    seg, hidden = ltp.seg(sents)
  File "C:\Users\Merli\anaconda3\lib\site-packages\ltp\ltp.py", line 40, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Merli\anaconda3\lib\site-packages\ltp\ltp.py", line 217, in seg
    is_pretokenized=is_preseged
  File "C:\Users\Merli\anaconda3\lib\site-packages\transformers\tokenization_utils_base.py", line 1832, in batch_encode_plus
    **kwargs,
  File "C:\Users\Merli\anaconda3\lib\site-packages\transformers\tokenization_utils_fast.py", line 343, in _batch_encode_plus
    batch_text_or_text_pairs, add_special_tokens=add_special_tokens, is_pretokenized=is_pretokenized
  File "C:\Users\Merli\anaconda3\lib\site-packages\tokenizers\implementations\base_tokenizer.py", line 249, in encode_batch
    return self._tokenizer.encode_batch(inputs, is_pretokenized, add_special_tokens)
ValueError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]
```

**Comment by AlongWY** [comment]
@HeroadZ 你这个叙述细节太少了，可能是有空格，给的句子格式不对等问题

**Comment by iamxinxin** [comment]
> 会自动导出ltp.onnx文件，你需要 CUDA_VISIBLE_DEVICES=-1 把 GPU ban 掉，onnx 在 windows 上会有问题

你好，我找了一圈还是没有找到LTP使用onnx加速的文档和代码？求指路
