### ISSUE TITLE
新的自定义字典功能有问题

### ISSUE THREAD

**Issue by BaoyanWang** [HIT-SCIR/ltp#383]
Traceback (most recent call last):
  File "ltp_test.py", line 19, in <module>
    segment, hidden = ltp.seg(["他去长江大桥。"])
  File "/datadrive/wangby21/ltp_learn/ltp/ltp/ltp.py", line 40, in wrapper
    return func(*args, **kwargs)
  File "/datadrive/wangby21/ltp_learn/ltp/ltp/ltp.py", line 181, in seg
    matching = self.seg_with_dict(inputs)
  File "/datadrive/wangby21/ltp_learn/ltp/ltp/ltp.py", line 151, in seg_with_dict
    matching_pos = self.trie.maximum_forward_matching(line)
  File "/datadrive/wangby21/ltp_learn/ltp/ltp/utils/ltp_trie.py", line 54, in maximum_forward_matching
    if start + end - 1 < text_len and self[text[start:end]]:
  File "/opt/conda/lib/python3.7/site-packages/pygtrie.py", line 860, in __getitem__
    node, _ = self._get_node(key_or_slice)
  File "/opt/conda/lib/python3.7/site-packages/pygtrie.py", line 553, in _get_node
    raise KeyError(key)
KeyError: '他'

前向最大匹配中使用了个trie树的字典导致：改为下面这样，自定义词典依然没有生效：
if start + end - 1 < text_len and (text[start:end] in self) and self[text[start:end]]:

text:   他去长江大桥。
self:  Trie(负重前行: True, 长江大桥: True)
[['他', '去', '长江', '大桥', '。']] [[[], [('A0', 0, 0), ('A1', 2, 3)], [], [], []]]

**Comment by AlongWY** [comment]
感谢您的反馈，我们也还在对代码功能进行测试，预计很快解决该问题

**Comment by BaoyanWang** [comment]
我解决了，
这一行改成这个
if start + end - 1 < text_len and (text[start:start+end] in self) and self[text[start:start+end]]:
你的end是窗口大小，所以结束应该是start_end

**Comment by AlongWY** [comment]
我写了代码，你可以试试新的

**Comment by carfly** [comment]
谢谢反馈！v4.0.8版本修复了该问题。

-Wanxiang (http://ir.hit.edu.cn/~car/)
