### ISSUE TITLE
我发现，分词功能对输入的语句有长度限制，好像是大于550个字符的直接报错。

### ISSUE THREAD

**Issue by haowuliao** [HIT-SCIR/ltp#388]
使用Base(v2)，对“观鱼村村民熊菊根多次反映诉求:一是观鱼村村委会将其鱼塘提挖断造成了巨额损失,要求村委会对鱼塘养鱼损失进行赔偿。2017年3月和11月熊菊根分别向西湖区法院、南昌市中级人民法院提起诉讼,法院判决观鱼村村委会赔付熊菊根鱼塘损失30000元。二是2013年其个人办理社保全额缴纳了73145.76元,要求享受桃花镇失地农民养老社保待遇,退回应由国家补助部分。经镇人社所核实,熊菊根属第三类可参保村民,根据相关文件精神,其于2013年2月全额缴纳的经费,按照参保缴费标准,个人应出40%,市财政应出资60%。三是拆迁时其拆迁房屋少核算了9.13平米,要求进行补偿。经城建办、观鱼村村委会核实,熊菊根于2009年9月1日与观鱼村签订了拆迁补偿协议,签约还建房安置总面积为617.46平米。2015年观鱼村安置房分配共分得6套住房,安置总面积为656.62平米,其中超出协议安置面积39.16平米以3750元/平米购买。此诉求城建办、观鱼村村委会多次查找熊菊根当年拆迁房屋调查摸底等原始材料,拟对其反映情况进行核实,但镇城建办及观鱼村均未找到其房屋的原始档案,而熊菊根一直要求解决此诉求。另,熊菊根在2012年11月曾因个人缴纳社保事宜向观鱼村委会借款10万元,其本人多次要求用上诉三点诉求的补偿款偿还村委会10万元的借款。” ， 这段话的前550个字符 进行分词，会直接报：
Traceback (most recent call last):

  File "<ipython-input-51-18c539ebc1b3>", line 1, in <module>
    seg, hidden = self.ltp.seg([x2])

  File "C:\Users\c102010\AppData\Roaming\Python\Python37\site-packages\ltp\ltp.py", line 39, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\c102010\AppData\Roaming\Python\Python37\site-packages\ltp\ltp.py", line 146, in seg
    token_type_ids=token_type_ids

  File "D:\ProgramData\Anaconda3\envs\py3.7\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)

  File "C:\Users\c102010\AppData\Roaming\Python\Python37\site-packages\transformers\modeling_electra.py", line 323, in forward
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds

  File "D:\ProgramData\Anaconda3\envs\py3.7\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)

  File "C:\Users\c102010\AppData\Roaming\Python\Python37\site-packages\transformers\modeling_bert.py", line 179, in forward
    position_embeddings = self.position_embeddings(position_ids)

  File "D:\ProgramData\Anaconda3\envs\py3.7\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)

  File "D:\ProgramData\Anaconda3\envs\py3.7\lib\site-packages\torch\nn\modules\sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)

  File "D:\ProgramData\Anaconda3\envs\py3.7\lib\site-packages\torch\nn\functional.py", line 1724, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)

IndexError: index out of range in self

理论上长度限制不是应该是510吗？

**Comment by AlongWY** [comment]
实际上也是510，但是在输入时进行tokenize时，对于数字和英文会产生子词，所以使用字符数估计长度并不准确，另外这段话可以先进行分句操作来避免报错。
