### ISSUE TITLE
示例分词结果不正确

### ISSUE THREAD

**Issue by ZOUG** [HIT-SCIR/ltp#402]
**运行环境：** Windows 10, Anaconda (conda 4.8.4), Python 3.8, PyTorch 1.6.0 + CUDA 10.2, LTP 4.0.8, transformers 3.0.2

刚建立了一个新conda环境试用LTP，具体步骤如下
（1）建立新环境：`conda create --name <conda_env_name> python=3.8`
（2）从conda安装部分依赖包：
```
conda activate <conda_env_name>
conda config --append channels conda-forge --env
conda install pytorch torchtext=0.5.0 cudatoolkit=10.2 -c pytorch
conda install pygtrie tornado fire pysnooper sacremoses toml regex packaging future filelock
```
（3）安装LTP：`<conda_env_path>\scripts\pip install ltp`
（4）下载模型文件到本地目录data\models并解压缩到tiny/small/base子目录下。
安装后**运行示例结果不正确。**

**不执行（2）中的最后一步直接安装LTP输出结果相同。**

**代码**
```
from ltp import LTP
ltp = LTP(r"data\models\tiny")
seg, _ = ltp.seg(["他叫汤姆去拿外衣。"])
print(seg)
```
**输出**
`[['他', '叫', '汤', '姆', '去', '拿', '外', '衣', '。']]`

**Comment by AlongWY** [comment]
你试试左斜杠？

**Comment by ZOUG** [comment]
> 你试试左斜杠？

运行[LTP文档分词示例](http://ltp.ai/docs/quickstart.html#id6)会抛异常。

```
seg, _ = ltp.seg(["他/叫/汤姆/去/拿/外衣/。".split('/')])
print(seg)
```

输出：
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Develop\Anaconda\envs\CN-NLP\lib\site-packages\ltp\ltp.py", line 40, in wrapper
    return func(*args, **kwargs)
  File "D:\Develop\Anaconda\envs\CN-NLP\lib\site-packages\ltp\ltp.py", line 214, in seg
    tokenized = self.tokenizer.batch_encode_plus(
  File "D:\Develop\Anaconda\envs\CN-NLP\lib\site-packages\transformers\tokenization_utils_base.py", line 1815, in batch_encode_plus
    return self._batch_encode_plus(
  File "D:\Develop\Anaconda\envs\CN-NLP\lib\site-packages\transformers\tokenization_utils_fast.py", line 335, in _batch_encode_plus
    encodings = self._tokenizer.encode(
  File "D:\Develop\Anaconda\envs\CN-NLP\lib\site-packages\tokenizers\implementations\base_tokenizer.py", line 212, in encode
    return self._tokenizer.encode(sequence, pair, is_pretokenized, add_special_tokens)
ValueError: TextInputSequence must be str
```

**Comment by AlongWY** [comment]
我的意思是ltp的参数，ltp=LTP("path/to/ltp")

**Comment by ZOUG** [comment]
> 我的意思是ltp的参数，ltp=LTP("path/to/ltp")

没用，结果一样。另外，如果输入路径下找不到模型程序会抛`FileNotFoundError`异常，不可能正确执行输出结果。

**Comment by AlongWY** [comment]
@ZOUG 你可以先看下#363，另外模型可以不解压进行加载，如果仍然不能解决，你可以给我发邮件在QQ或者微信上联系

**Comment by ZOUG** [comment]
> @ZOUG 你可以先看下#363，另外模型可以不解压进行加载，如果仍然不能解决，你可以给我发邮件在QQ或者微信上联系

那个问题是模型载入失败。我这是模型已经载入成功了，但是分词结果不对。

**Comment by AlongWY** [comment]
确认是模型下载后已损坏，之后将加入校验
