### ISSUE TITLE
Missing key(s) in state_dict: "pretrained.embeddings.position_ids".

### ISSUE THREAD

**Issue by appleyuchi** [HIT-SCIR/ltp#406]
代码如下:
`from ltp import LTP`
`ltp=LTP()`
`seg, hidden = ltp.seg(["那青年横削三剑。"])`
`sdp = ltp.sdp(hidden, graph=True)`
报错为:
Traceback (most recent call last):
  File "/home/appleyuchi/bigdata/spark-3.0.0-bin-hadoop3.2/python/test.py", line 2, in <module>
    ltp=LTP()
  File "/home/appleyuchi/anaconda3/lib/python3.6/site-packages/ltp/ltp.py", line 121, in __init__
    self.model.load_state_dict(ckpt['model'])
  File "/home/appleyuchi/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SimpleMultiTaskModel:
	Missing key(s) in state_dict: "pretrained.embeddings.position_ids". 

Process finished with exit code 1

**Comment by AlongWY** [comment]
这个问题是由于 huggingface/transformers 更新了模型的结构导致的，增加了一个带有默认值的position_ids，现在已经更新修复了 #403
