### ISSUE TITLE
分词出现报错，输入应该是str而不是list。

### ISSUE THREAD

**Issue by zhanghua2018** [HIT-SCIR/ltp#434]
D:\Anaconda3\python.exe "D:/Code/Unsupervised Linguistics-based Chinese Open Relation Extraction(zh)/code/ltp_test.py"
[['他', '叫', '汤姆', '去', '拿', '外衣', '。']]
<class 'list'>
Traceback (most recent call last):
  File "D:/Code/Unsupervised Linguistics-based Chinese Open Relation Extraction(zh)/code/ltp_test.py", line 37, in <module>
    segment, hidden = ltp.seg(["他/叫/汤姆/去/拿/外衣/。".split('/')])
  File "D:\Anaconda3\lib\site-packages\ltp\ltp.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\ltp\ltp.py", line 218, in seg
    tokenized = self.tokenizer.batch_encode_plus(
  File "D:\Anaconda3\lib\site-packages\transformers\tokenization_utils_base.py", line 2122, in batch_encode_plus
    return self._batch_encode_plus(
  File "D:\Anaconda3\lib\site-packages\transformers\tokenization_utils_fast.py", line 372, in _batch_encode_plus
    encodings = self._tokenizer.encode(
  File "D:\Anaconda3\lib\site-packages\tokenizers\implementations\base_tokenizer.py", line 212, in encode
    return self._tokenizer.encode(sequence, pair, is_pretokenized, add_special_tokens)
ValueError: TextInputSequence must be str

LTP文档中分词的示例是否有误？[http://ltp.ai/docs/quickstart.html#id2](url)
![分词](https://user-images.githubusercontent.com/37328560/98510528-40aa1e80-229e-11eb-876c-0ca0e51f6d0a.JPG)

**Comment by AlongWY** [comment]
多谢您的反馈，这里应该有一个 `is_preseged=True` 参数
