### ISSUE TITLE
dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by liuchenbaidu** [HIT-SCIR/ltp#435]
python 3.6.3
ltp 4.0.9
GCC 4.8.4

Traceback (most recent call last):
  File "pre_app.py", line 39, in <module>
    from wenlp.sentence_analyser import process_long_sentence,sub_pre_comma,del_nonsense,change_negative_is_positive
  File "/data/welab/nlp/speech_bot_venv/venv/lib/python3.6/site-packages/webot_nlp-1.0-py3.6.egg/wenlp/sentence_analyser.py", line 4, in <module>
    from ltp import LTP
  File "/data/welab/nlp/speech_bot_venv/venv/lib/python3.6/site-packages/ltp/__init__.py", line 7, in <module>
    from .data import Dataset
  File "/data/welab/nlp/speech_bot_venv/venv/lib/python3.6/site-packages/ltp/data/__init__.py", line 5, in <module>
    from .vocab import Vocab
  File "/data/welab/nlp/speech_bot_venv/venv/lib/python3.6/site-packages/ltp/data/vocab.py", line 9, in <module>
    import torch
  File "/data/welab/nlp/speech_bot_venv/venv/lib/python3.6/site-packages/torch/__init__.py", line 188, in <module>
    _load_global_deps()
  File "/data/welab/nlp/speech_bot_venv/venv/lib/python3.6/site-packages/torch/__init__.py", line 141, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen: cannot load any more object with static TLS

**Comment by AlongWY** [comment]
这里看上去是 pytorch 报的错误？
