### ISSUE TITLE
ltp4.1.0模型加载出错

### ISSUE THREAD

**Issue by MachineWei** [HIT-SCIR/ltp#443]
环境：python3.6, torch1.2.0, transformers3.4.0,  ltp-4.1.0，加载v3模型(tiny, small, base)时出现：
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'eddings.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 2299, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 1035, in frombuf
    chksum = nti(buf[148:156])
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\site-packages\torch\serialization.py", line 555, in _load
    return legacy_load(f)
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\site-packages\torch\serialization.py", line 466, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 2311, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\site-packages\ltp\frontend.py", line 122, in __init__
    ckpt = torch.load(os.path.join(path, "ltp.model"), map_location=self.device)
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\site-packages\torch\serialization.py", line 559, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: F:\workspaces\python\models\ltp4base_v3\ltp.model is a zip archive (did you mean to use torch.jit.load()?)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'eddings.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 2299, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 1035, in frombuf
    chksum = nti(buf[148:156])
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\site-packages\torch\serialization.py", line 555, in _load
    return legacy_load(f)
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\site-packages\torch\serialization.py", line 466, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\tarfile.py", line 2311, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\site-packages\ltp\frontend.py", line 125, in __init__
    ckpt = torch.load(os.path.join(path, "ltp.model"), map_location=self.device)
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "D:\ProgramData\Anaconda3\envs\work_py36\lib\site-packages\torch\serialization.py", line 559, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: F:\workspaces\python\models\ltp4base_v3\ltp.model is a zip archive (did you mean to use torch.jit.load()?)>>>

**Comment by AlongWY** [comment]
pytorch 更改了 ckpt 的保存方式，这是使用新方式保存的 ckpt, 之后会采用旧版本的保存方法重新发布一下模型

**Comment by AlongWY** [comment]
已经更新了模型
