### ISSUE TITLE
Mac上import 报错

### ISSUE THREAD

**Issue by zhoudoufu** [HIT-SCIR/ltp#516]
ltp版本 ltp==4.1.4.post1
安装命令 pip install ltp
python 3.8.3+
macOS Mojave 10.14.4
报错信息
>>> import ltp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.pyenv/versions/wordlink/lib/python3.8/site-packages/ltp/__init__.py", line 8, in <module>
    from . import nn, utils
  File "/Users/.pyenv/versions/wordlink/lib/python3.8/site-packages/ltp/utils/__init__.py", line 11, in <module>
    from .deploy_model import deploy_model
  File "/Users/.pyenv/versions/wordlink/lib/python3.8/site-packages/ltp/utils/deploy_model.py", line 11, in <module>
    from transformers import AutoConfig
  File "/Users/.pyenv/versions/wordlink/lib/python3.8/site-packages/transformers/__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "/Users/.pyenv/versions/wordlink/lib/python3.8/site-packages/transformers/dependency_versions_check.py", line 36, in <module>
    from .file_utils import is_tokenizers_available
  File "/Users/.pyenv/versions/wordlink/lib/python3.8/site-packages/transformers/file_utils.py", line 51, in <module>
    from huggingface_hub import HfApi, HfFolder, Repository
  File "/Users/.pyenv/versions/wordlink/lib/python3.8/site-packages/huggingface_hub/__init__.py", line 31, in <module>
    from .file_download import cached_download, hf_hub_url
  File "/Users/.pyenv/versions/wordlink/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 37, in <module>
    if tuple(int(i) for i in _PY_VERSION.split(".")) < (3, 8, 0):
  File "/Users/.pyenv/versions/wordlink/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 37, in <genexpr>
    if tuple(int(i) for i in _PY_VERSION.split(".")) < (3, 8, 0):
ValueError: invalid literal for int() with base 10: '3+'

能否提供Mac系统的安装方式建议？

**Comment by AlongWY** [comment]
可以说明一下 transformers 的版本吗？
看这个错误是 transformers 的错误

**Comment by zhoudoufu** [comment]
> 可以说明一下 transformers 的版本吗？
> 看这个错误是 transformers 的错误

transformers 4.6.1 会报以上错误，改用4.5.1就OK了
