### ISSUE TITLE
4.2 版本报错

### ISSUE THREAD

**Issue by Joseph98-AI** [HIT-SCIR/ltp#579]
分词测试报错：
win10系统 anaconda创建环境
```
from ltp import LTP
ltp = LTP()
words = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks = ["cws"], return_dict = True)
```
```
TypeError: __init__() got an unexpected keyword argument 'cws'
```
发现问题：
https://github.com/HIT-SCIR/ltp/blob/134f1606e35506b1272f5538f40aac1daa1c27a8/python/interface/ltp/generic.py#L107

```
# V4.2
class LTPOutput(ModelOutput):
    cws = None
    pos = None
    ner = None
    srl = None
    dep = None
    sdp = None
    sdpg = None
```
改成下面就正常输出 LTPOutput(cws=['他', '叫', '汤姆', '去', '拿', '外衣', '。'], pos=None, ner=None, srl=None, dep=None, sdp=None, sdpg=None)
```
# main 分支
class LTPOutput(ModelOutput):
    cws: Optional[Union[List[str], List[List[str]]]] = None
    pos: Optional[Union[List[str], List[List[str]]]] = None
    ner: Optional[Union[List[str], List[List[str]]]] = None
    srl: Optional[Union[List[str], List[List[str]]]] = None
    dep: Optional[Union[List[str], List[List[str]]]] = None
    sdp: Optional[Union[List[str], List[List[str]]]] = None
    sdpg: Optional[Union[List[str], List[List[str]]]] = None
```

**Comment by AlongWY** [comment]
最新版本改过来了

**Comment by Joseph98-AI** [comment]
> 
4.2.0 版本我重新安装了测试分词，LTPOutput 输出的数据处理还是有问题
```
from ltp import LTP

ltp = LTP()
output = ltp.pipeline("他叫汤姆去拿外衣。", tasks = ["cws"])
print(output.cws)

Traceback (most recent call last):
  File ".\test.py", line 6, in <module>
    output = ltp.pipeline("他叫汤姆去拿外衣。", tasks = ["cws"])
  File "C:\Users\Eric\.conda\envs\pytorch\lib\site-packages\ltp\nerual.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Eric\.conda\envs\pytorch\lib\site-packages\ltp\nerual.py", line 171, in pipeline
    output = LTPOutput(**{task: predict[0] for task, predict in store.items()})
TypeError: __init__() got an unexpected keyword argument 'cws'
```

**Comment by AlongWY** [comment]
不要安装 4.2.0 版本啊，安装 最新的 4.2.7 版本 `pip install ltp==4.2.7 -i https://pypi.org/simple`
