### ISSUE TITLE
依存句法分析出错

### ISSUE THREAD

**Issue by wjx-git** [HIT-SCIR/ltp#608]
版本：
ltp                                4.2.11.post1
ltp-core                           0.1.2
ltp-extension                      0.1.9
transformers                       4.24.0
torch                              1.13.0

运行官方示例：
ltp = LTP()
output = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks=["cws", "pos", "dep", "sdp"])
print(output.cws)  # print(output[0]) / print(output['cws']) # 也可以使用下标访问
print(output.pos)
print(output.sdp)

报错信息：
Traceback (most recent call last):
  File "D:\Projects\PretrainModel\PretrainTask\t.py", line 45, in <module>
    output = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks=["cws", "pos", "dep", "sdp"])
  File "D:\Users\80370280\Anaconda3\lib\site-packages\ltp\nerual.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "D:\Users\80370280\Anaconda3\lib\site-packages\ltp\nerual.py", line 187, in pipeline
    store[task] = self.post[task](result, hidden, store, inputs, tokenized)
  File "D:\Users\80370280\Anaconda3\lib\site-packages\ltp\nerual.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "D:\Users\80370280\Anaconda3\lib\site-packages\ltp\nerual.py", line 436, in _dep_post
    s_arc = s_arc.view(-1).cpu().numpy()
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by AlongWY** [comment]
感谢反馈，ltp 4.2.11.post2 已修复
