### ISSUE TITLE
在进行中文分句时为什么对.也进行了分词

### ISSUE THREAD

**Issue by Alex-DeepL** [HIT-SCIR/ltp#714]
我的数据是：1.联通华盛电商分公司办公室内的灯火彻夜不熄，这已经成为常态。这句话正常是一句话的。但是给我返回的结果是[1.,联通华盛电商分公司办公室内的灯火彻夜不熄，这已经成为常态。]两句话，请问这个问题如何解决

**Comment by AlongWY** [comment]
有代码的例子吗？

**Comment by Alex-DeepL** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Feng ***@***.***&gt;; 
发送时间: 2024年10月12日(星期六) 上午10:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HIT-SCIR/ltp] 在进行中文分句时为什么对.也进行了分词 (Issue #714)














 
有代码的例子吗？

**Comment by AlongWY** [comment]
试试这段代码，应该是没有关闭英文分词配置

```python
from ltp import StnSplit

spliter = StnSplit()
spliter.use_en = False
sents = spliter.split("1.联通华盛电商分公司办公室内的灯火彻夜不熄，这已经成为常态。")
print(sents)
```

**Comment by Alex-DeepL** [comment]
好的谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Feng ***@***.***&gt;; 
发送时间: 2024年10月12日(星期六) 上午10:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HIT-SCIR/ltp] 在进行中文分句时为什么对.也进行了分词 (Issue #714)














 
试试这段代码，应该是没有关闭英文分词配置
 from ltp import StnSplit spliter = StnSplit() spliter.use_en = False sents = spliter.split("1.联通华盛电商分公司办公室内的灯火彻夜不熄，这已经成为常态。") print(sents)

**Comment by Alex-DeepL** [comment]
感谢感谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HIT-SCIR/ltp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月12日(星期六) 上午10:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HIT-SCIR/ltp] 在进行中文分句时为什么对.也进行了分词 (Issue #714)





 
试试这段代码，应该是没有关闭英文分词配置
 from ltp import StnSplit spliter = StnSplit() spliter.use_en = False sents = spliter.split("1.联通华盛电商分公司办公室内的灯火彻夜不熄，这已经成为常态。") print(sents)

**Comment by Alex-DeepL** [comment]
大佬，你们也在参加那个df上的比赛啊？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Feng ***@***.***&gt;; 
发送时间: 2024年10月12日(星期六) 上午10:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HIT-SCIR/ltp] 在进行中文分句时为什么对.也进行了分词 (Issue #714)














 
试试这段代码，应该是没有关闭英文分词配置
 from ltp import StnSplit spliter = StnSplit() spliter.use_en = False sents = spliter.split("1.联通华盛电商分公司办公室内的灯火彻夜不熄，这已经成为常态。") print(sents)

**Comment by AlongWY** [comment]
什么比赛，应该是没有参加

**Comment by Alex-DeepL** [comment]
大佬，为什么我在分词时加入自己的此表就报错。Traceback (most recent call last):
&nbsp; File "/model/workspace/lwl/competiton/utils/bm25_search_artical.py", line 64, in <module&gt;
&nbsp; &nbsp; print(get_clean_content_words("../data/docx/AF01.docx"))
&nbsp; File "/model/workspace/lwl/competiton/utils/bm25_search_artical.py", line 53, in get_clean_content_words
&nbsp; &nbsp; words_list.extend([word for word in split_sentence_to_words(sentence) if
&nbsp; File "/model/workspace/lwl/competiton/utils/bm25_search_artical.py", line 44, in split_sentence_to_words
&nbsp; &nbsp; return ltp.pipeline(sentence, tasks=["cws"])["cws"]
&nbsp; File "/root/anaconda3/envs/competition/lib/python3.8/site-packages/ltp/nerual.py", line 24, in wrapper
&nbsp; &nbsp; return func(*args, **kwargs)
&nbsp; File "/root/anaconda3/envs/competition/lib/python3.8/site-packages/ltp/nerual.py", line 185, in pipeline
&nbsp; &nbsp; store[task] = self.post[task](result, hidden, store, inputs, tokenized)
&nbsp; File "/root/anaconda3/envs/competition/lib/python3.8/site-packages/ltp/nerual.py", line 24, in wrapper
&nbsp; &nbsp; return func(*args, **kwargs)
&nbsp; File "/root/anaconda3/envs/competition/lib/python3.8/site-packages/ltp/nerual.py", line 282, in _cws_post
&nbsp; &nbsp; words = [self.hook.hook(t, w) for t, w in zip(inputs, words)]
&nbsp; File "/root/anaconda3/envs/competition/lib/python3.8/site-packages/ltp/nerual.py", line 282, in <listcomp&gt;
&nbsp; &nbsp; words = [self.hook.hook(t, w) for t, w in zip(inputs, words)]
RuntimeError: Invalid UTF-8 sentence!这是错误信息




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Feng ***@***.***&gt;; 
发送时间: 2024年10月14日(星期一) 下午3:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HIT-SCIR/ltp] 在进行中文分句时为什么对.也进行了分词 (Issue #714)














 
Closed #714 as completed.
